name: Push Docker Images

on: [push, pull_request]
  # push:
  #   branches:
  #     - master
jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Push docker image
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run : ./.github/workflows/deployment_prs.sh
